import Head from 'next/head'
import React from "react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Beacon App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to Beacon Project</h1>
    </div>
  )
}
